### ISSUE TITLE
#import <Cordova/NSData+Base64.h>

### ISSUE THREAD

**Issue by Boonda-P** [iakashpaul/iOSRTCApp#1]
works on browser, but when I try to run ios I get error:

/opt/newiosapp/iOSRTCApp/platforms/ios/iOSRTCApp/Plugins/cordova-plugin-camera/CDVCamera.m:23:9: fatal error: 'Cordova/NSData+Base64.h' file not found
#import <Cordova/NSData+Base64.h>
        ^
1 warning and 1 error generated.

** BUILD FAILED **

The following build commands failed:
        CompileC build/iOSRTCApp.build/Debug-iphoneos/iOSRTCApp.build/Objects-normal/armv7/CDVCamera.o iOSRTCApp/Plugins/cordova-plugin-camera/CDVCamera.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/opt/newiosapp/iOSRTCApp/platforms/ios/cordova/build-debug.xcconfig,-project,iOSRTCApp.xcodeproj,-target,iOSRTCApp,-configuration,Debug,-destination,platform=iOS,build,CONFIGURATION_BUILD_DIR=/opt/newiosapp/iOSRTCApp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/opt/newiosapp/iOSRTCApp/platforms/ios/build/sharedpch

**Comment by iakashpaul** [comment]
Have you added the bridging header?

**Comment by Boonda-P** [comment]
Not really sure how I would go about doing that.

**Comment by iakashpaul** [comment]
Add this to platforms/ios/[PROJECT_NAME]/Bridging-Header.h
#import "Plugins/cordova-plugin-iosrtc/cordova-plugin-iosrtc-Bridging-Header.h"

**Comment by Boonda-P** [comment]
same error still occurs

**Comment by iakashpaul** [comment]
Whats the xcode version?

**Comment by Boonda-P** [comment]
8.2.1

**Comment by iakashpaul** [comment]
Did you select 'later' on the prompts by Xcode to convert the syntax?

**Comment by Boonda-P** [comment]
yes

**Comment by iakashpaul** [comment]
Are the other dependencies installed as well?

**Comment by iakashpaul** [comment]
Nothing else is required. Can you put the contents of config.xml here.

**Comment by Boonda-P** [comment]
<?xml version='1.0' encoding='utf-8'?>
<widget id="com.akashpaul.iosrtcapp" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>iOSRTCApp</name>
    <description>
        Google's AppRTC application adapted to iOS devices using cordova-plugin-iosrtc.
    </description>
    <author email="inaki.baz@eface2face.com" href="https://eface2face.com">
        Iñaki Baz Castillo at eFace2Face, inc.
    </author>
    <content src="index.html" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="Orientation" value="portrait" />
    <preference name="EnableViewportScale" value="true" />
    <preference name="StatusBarOverlaysWebView" value="false" />
    <plugin name="cordova-plugin-whitelist" version="1.0.0" />
    <access origin="*" subdomains="true" uri="*"  />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <hook src="hooks/iosrtc-swift-support.js" type="after_platform_add" />
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <config-file parent="NSCameraUsageDescription" target="*-Info.plist">
            <string>Blink uses your camera to make video calls.</string>
        </config-file>
        <config-file parent="NSContactsUsageDescription" target="*-Info.plist">
            <string>Blink needs access to your contacts in order to be able to call them.</string>
        </config-file>
        <config-file parent="NSMicrophoneUsageDescription" target="*-Info.plist">
            <string>Blink uses your microphone to make calls.</string>
        </config-file>
    </platform>
    <plugin name="cordova-plugin-device" version="^1.0.1" />
    <plugin name="cordova-plugin-iosrtc" version="^3.2.2" />
    <plugin name="cordova-plugin-camera" spec="https://github.com/eface2face/cordova-plugin-camera" />
    <plugin name="cordova-plugin-iosrtc-ios10" spec="https://github.com/seiryow/cordova-plugin-iosrtc-ios10" />
</widget>

**Comment by Boonda-P** [comment]
I apologize for the lack of formatting
